# These are supported funding model platforms

github: rodrigomarcelo643
patreon: rodrigomarcelo643
ko_fi: rodrigomarcelo643
custom: ['https://github.com/rodrigomarcelo643/vanilla-php-mvc-starterkit']
